services:
  - type: web
    name: storyscout-website
    runtime: node
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: "true"
